### ISSUE TITLE
ColorMatch completely broken

### ISSUE THREAD

**Issue by addstar** [AddstarMC/ColorMatch#2]
I think this has been failing since 1.13 but always forgot to report it. This error happens when the game starts. SuperSign words don't update and game doesn't run.

```
2019-07-06 22:36:50 [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Minigames v1.13-SNAPSHOT-281
java.lang.NoSuchMethodError: au.com.addstar.signmaker.TextSign.setMaterial(Lorg/bukkit/material/MaterialData;)V
        at com.comze_instancelabs.colormatch.GameBoard.updateSigns(GameBoard.java:104) ~[?:?]
        at com.comze_instancelabs.colormatch.GameBoard.joinArena(GameBoard.java:147) ~[?:?]
        at com.comze_instancelabs.colormatch.ColorMatchMechanic.onJoinMinigame(ColorMatchMechanic.java:136) ~[?:?]
        at au.com.mineauz.minigames.MinigamePlayerManager.joinMinigame(MinigamePlayerManager.java:116) ~[?:?]
        at au.com.mineauz.minigames.signs.JoinSign.signUse(JoinSign.java:111) ~[?:?]
        at au.com.mineauz.minigames.signs.SignBase.signUse(SignBase.java:98) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-624]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:320) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:466) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1348) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-624]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

```
2019-07-06 22:40:46 [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Minigames v1.13-SNAPSHOT-281
java.lang.NoSuchFieldError: COLOURED_DUST
        at com.comze_instancelabs.colormatch.ColorMatchMechanic.onPlayerMove(ColorMatchMechanic.java:64) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor219.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-624]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1063) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-624]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by addstar** [comment]
Ignore the above error - We weren't running the latest build.

On the latest build, it's still not working and the error is pretty unhelpful:
```
2019-07-06 23:03:37 [Server thread/INFO]: Enabling ColorMatch v1.9.2-SNAPHOT-72
2019-07-06 23:03:37 [Server thread/ERROR]: Error occurred while enabling ColorMatch v1.9.2-SNAPHOT-72 (Is it up to date?)
java.lang.StackOverflowError: null
        at au.com.mineauz.minigames.Minigames.log(Minigames.java:404) ~[?:?]
        at au.com.mineauz.minigames.Minigames.log(Minigames.java:404) ~[?:?]
        at au.com.mineauz.minigames.Minigames.log(Minigames.java:404) ~[?:?]
        at au.com.mineauz.minigames.Minigames.log(Minigames.java:404) ~[?:?]
        at au.com.mineauz.minigames.Minigames.log(Minigames.java:404) ~[?:?]
        at au.com.mineauz.minigames.Minigames.log(Minigames.java:404) ~[?:?]
[repeated hundreds of times]
...
2019-07-06 23:03:37 [Server thread/INFO]: Disabling ColorMatch v1.9.2-SNAPHOT-72
```

**Comment by addstar** [comment]
Closing because this is false - We haven't updated or tested new versions of things

I will re-open a new Issue with better information.
